import hashlib
import sqlite3
import tempfile
import unittest
from pathlib import Path

from adapters.aws.postgres import PostgresRequest
from adapters.database.migrations import collect_sql_migrations
from adapters.database.sqlite_snapshot import compile_sqlite_snapshot
from adapters.local.docker import LocalDockerAdapter
from application.agent import DeploymentTools
from application.consistency import check_source_change_scope, check_sqlite_migration_consistency
from application.deployment_core import make_plan, source_digest
from application.infrastructure import (
    inspect_infrastructure,
    preflight_sqlite_conversion,
    validate_infrastructure,
)
from application.source_transform import source_transform_record
from engine.deployment_policy import deployment_policy


class SqliteSnapshotTests(unittest.TestCase):
    def test_compiles_schema_rows_and_row_count_checks_without_editing_source(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            source = root / 'source.db'
            with sqlite3.connect(source) as connection:
                connection.execute('CREATE TABLE posts (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL)')
                connection.executemany('INSERT INTO posts (title) VALUES (?)', [("O'Reilly",), ('한글',)])
            before = source.read_bytes()
            snapshot = compile_sqlite_snapshot(source)
            self.assertEqual(snapshot.source_sha256, hashlib.sha256(before).hexdigest())
            self.assertEqual(snapshot.row_counts, {'posts': 2})
            self.assertEqual(snapshot.schema['posts'][0],
                             {'name': 'id', 'type': 'INTEGER', 'primary_key': True, 'required': False})
            self.assertIn('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', snapshot.sql)
            self.assertIn("'O''Reilly'", snapshot.sql)
            self.assertIn('COUNT(*) FROM "posts") = 2', snapshot.sql)
            self.assertIn('expected EXCEPT ALL SELECT * FROM actual', snapshot.sql)
            self.assertIn('actual EXCEPT ALL SELECT * FROM expected', snapshot.sql)
            self.assertEqual(source.read_bytes(), before)
            project = root / 'app'
            (project / 'migrations').mkdir(parents=True)
            (project / 'migrations' / '0000_sky_sqlite_import.sql').write_text(snapshot.sql)
            self.assertEqual(len(collect_sql_migrations(project).migrations), 1)

    def test_value_verification_supports_null_duplicate_and_empty_tables(self):
        with tempfile.TemporaryDirectory() as folder:
            source = Path(folder) / 'source.db'
            with sqlite3.connect(source) as connection:
                connection.execute('CREATE TABLE readings (value INTEGER, note TEXT)')
                connection.executemany('INSERT INTO readings VALUES (?, ?)',
                                       [(None, None), (7, 'same'), (7, 'same')])
                connection.execute('CREATE TABLE empty_table (value TEXT)')
            snapshot = compile_sqlite_snapshot(source)
            self.assertEqual(snapshot.row_counts, {'empty_table': 0, 'readings': 3})
            self.assertIn('CAST(NULL AS BIGINT), CAST(NULL AS TEXT)', snapshot.sql)
            self.assertIn('COUNT(*) FROM "empty_table") = 0', snapshot.sql)

    def test_rejects_unsupported_schema_and_values(self):
        cases = [
            ('CREATE TABLE posts (id INTEGER PRIMARY KEY, score REAL)', None),
            ('CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT DEFAULT "x")', None),
            ('CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT CHECK(length(title)>0))', None),
            ('CREATE TABLE posts (id INTEGER PRIMARY KEY, payload BLOB)', None),
            ('CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT)', 'CREATE INDEX i ON posts(title)'),
            ('CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT NOT NULL ON CONFLICT IGNORE)', None),
        ]
        for ddl, extra in cases:
            with self.subTest(ddl=ddl), tempfile.TemporaryDirectory() as folder:
                source = Path(folder) / 'source.db'
                with sqlite3.connect(source) as connection:
                    connection.execute(ddl)
                    if extra:
                        connection.execute(extra)
                with self.assertRaises(ValueError):
                    compile_sqlite_snapshot(source)

    def test_rejects_primary_key_that_cannot_seed_postgres_identity(self):
        with tempfile.TemporaryDirectory() as folder:
            source = Path(folder) / 'source.db'
            with sqlite3.connect(source) as connection:
                connection.execute('CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT)')
                connection.execute('INSERT INTO posts (id, title) VALUES (0, "zero")')
            with self.assertRaisesRegex(ValueError, '양수'):
                compile_sqlite_snapshot(source)

    def test_preserves_autoincrement_high_water_mark_after_deletion(self):
        with tempfile.TemporaryDirectory() as folder:
            source = Path(folder) / 'source.db'
            with sqlite3.connect(source) as connection:
                connection.execute('CREATE TABLE posts (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT)')
                connection.executemany('INSERT INTO posts (title) VALUES (?)', [('first',), ('second',)])
                connection.execute('DELETE FROM posts WHERE id = 2')
            snapshot = compile_sqlite_snapshot(source)
            self.assertIn('GREATEST(COALESCE(MAX("id"), 1), 2)', snapshot.sql)

    def test_rejects_wal_and_symlink(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            source = root / 'source.db'
            with sqlite3.connect(source) as connection:
                connection.execute('CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT)')
            alias = root / 'alias.db'
            alias.symlink_to(source)
            with self.assertRaisesRegex(ValueError, '일반 파일'):
                compile_sqlite_snapshot(alias)
            (root / 'source.db-wal').touch()
            with self.assertRaisesRegex(ValueError, 'WAL'):
                compile_sqlite_snapshot(source)

    def test_opt_in_working_copy_prepares_migration_then_requires_code_conversion(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            source = root / 'source'
            source.mkdir()
            (source / 'server.py').write_text('import sqlite3\n')
            (source / 'requirements.txt').write_text('flask\n')
            database = source / 'app.db'
            with sqlite3.connect(database) as connection:
                connection.execute('CREATE TABLE posts (id INTEGER PRIMARY KEY, title TEXT)')
                connection.execute('INSERT INTO posts (title) VALUES (?)', ('hello',))
            conversion, projected = preflight_sqlite_conversion(source, inspect_infrastructure(source))
            self.assertEqual(conversion['row_counts'], {'posts': 1})
            validate_infrastructure(projected, 'aws-ecs-express', postgres=True)
            request = PostgresRequest('demo-app', '123456789012', 'ap-northeast-2',
                                      'vpc-12345678', ('subnet-12345678', 'subnet-abcdef12'), 'sg-12345678')
            changes = []
            tools = DeploymentTools(source, root / 'work', 'a' * 16, {}, lambda *_: None,
                                    lambda **updates: changes.append(updates),
                                    adapter_factory=LocalDockerAdapter, target='aws-ecs-express',
                                    postgres_request=request, sqlite_conversion=conversion)
            self.assertTrue(tools.prepare_sqlite_migration()['prepared'])
            self.assertTrue(database.exists())
            self.assertFalse((tools.work / 'app.db').exists())
            self.assertEqual(len(collect_sql_migrations(tools.work).migrations), 1)
            self.assertNotIn('hello', str(changes))
            with self.assertRaisesRegex(ValueError, 'SQLite'):
                validate_infrastructure(inspect_infrastructure(tools.work), 'aws-ecs-express', postgres=True)
            (tools.work / 'server.py').write_text('import psycopg\n')
            (tools.work / 'requirements.txt').write_text('flask\npsycopg\n')
            validate_infrastructure(inspect_infrastructure(tools.work), 'aws-ecs-express', postgres=True)
            self.assertTrue(tools.prepare_sqlite_migration()['prepared'])
            compilation = {
                'compilation_id': 'comp-example', 'decision_revision': 1,
                'source_revision': source_digest(source),
                'target_plan': {'id': 'target-example', 'target': 'aws-ecs-express'},
            }
            plan = make_plan(tools.work, 'server.py', None, target='aws-ecs-express')
            record = source_transform_record(compilation, source, tools.work, plan)
            self.assertEqual(check_source_change_scope(record, source, conversion)['status'], 'pass')
            infrastructure_plan = {
                'target': 'aws-ecs-express',
                'conversion_pending': 'sqlite-to-postgresql',
                'database': {'binding': 'create', 'database_id': request.database_id},
                'resources': ['new RDS PostgreSQL', 'one-off SQL migration task'],
            }
            bundle = collect_sql_migrations(tools.work)
            policy = deployment_policy('aws-ecs-express', True, allow_data_migration=True)
            final_profile = inspect_infrastructure(tools.work)
            checked = check_sqlite_migration_consistency(
                infrastructure_plan, final_profile, source, conversion, bundle, request, policy)
            self.assertEqual(checked['status'], 'pass')
            self.assertEqual(checked['integrity']['protocol'], 'sqlite-snapshot-multiset-v1')
            self.assertEqual(checked['integrity']['bundle_digest'], bundle.digest)
            self.assertEqual(checked['integrity']['source_revision'], source_digest(source))
            self.assertEqual(checked['integrity']['prepared_revision'], source_digest(tools.work))
            self.assertEqual(checked['integrity']['row_counts'], conversion['row_counts'])
            with self.assertRaisesRegex(ValueError, 'CV-04.*approved'):
                check_sqlite_migration_consistency(
                    infrastructure_plan, final_profile, source, conversion, bundle, request,
                    deployment_policy('aws-ecs-express', True))
            with self.assertRaisesRegex(ValueError, 'CV-04.*execution plan'):
                check_sqlite_migration_consistency(
                    {**infrastructure_plan, 'conversion_pending': None}, final_profile,
                    source, conversion, bundle, request, policy)
            with self.assertRaisesRegex(ValueError, 'CV-04.*execution plan'):
                check_sqlite_migration_consistency(
                    {**infrastructure_plan, 'resources': ['new RDS PostgreSQL']}, final_profile,
                    source, conversion, bundle, request, policy)
            migration = tools.work / 'migrations' / '0000_sky_sqlite_import.sql'
            migration.write_text(migration.read_text() + '\nSELECT 1;\n')
            with self.assertRaisesRegex(ValueError, 'CV-04.*Scheduled SQL'):
                check_sqlite_migration_consistency(
                    infrastructure_plan, final_profile, source, conversion,
                    collect_sql_migrations(tools.work), request, policy)


if __name__ == '__main__':
    unittest.main()
